# Generated by Django 4.2.9 on 2024-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0002_alter_bilets_invoiceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId_Vvod', models.UUIDField()),
            ],
        ),
    ]
